services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.4
    container_name: elasticsearch
    networks:
      - PrviNetwork
    restart: always
    environment:
      - bootstrap.memory_lock=true
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - eslogs:/usr/share/elasticsearch/logs
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.8
    container_name: jaeger-collector
    networks:
      - PrviNetwork
    restart: always
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
    ports:
      - "14267:14267"
      - "14268:14268"
      - "9411:9411"
      - "14250:14250"
    depends_on:
      - elasticsearch
    command:
      - "--es.server-urls=http://elasticsearch:9200"

  jaeger-agent:
    image: jaegertracing/jaeger-agent:1.8
    container_name: jaeger-agent
    networks:
      - PrviNetwork
    restart: always
    environment:
      - COLLECTOR_HOST_PORT=jaeger-collector:14267
    ports:
      - "5775:5775/udp"
      - "5778:5778"
      - "6831:6831/udp"
      - "6832:6832/udp"
    depends_on:
      - jaeger-collector

  jaeger-query:
    image: jaegertracing/jaeger-query:1.8
    container_name: jaeger-query
    networks:
      - PrviNetwork
    restart: always
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
    ports:
      - "16686:16686"
    depends_on:
      - jaeger-collector
    command:
      - "--es.server-urls=http://elasticsearch:9200"
      - "--es.sniffer=false"
      - "--log-level=debug"

volumes:
  esdata:
  eslogs:

networks:
  PrviNetwork:
    external: true