global:
  resolve_timeout: 1m

route:
  group_by: ["alertname"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1d
  receiver: "slack-notifications"

  routes:
    - match:
        severity: warning
      receiver: "slack-notifications"
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1d

    - match:
        severity: error
      receiver: "slack-notifications"
      group_wait: 20s
      group_interval: 2m
      repeat_interval: 1h

    - match:
        severity: critical
      receiver: "slack-notifications"
      group_wait: 15s
      group_interval: 1m
      repeat_interval: 1h

templates:
  - "./template.tmpl"

receivers:
  - name: "email"
    email_configs:
      - to: "thuanlephuc152@gmail.com"
        from: "thuanlephuc152@gmail.com"
        smarthost: "smtp.gmail.com:587"
        auth_identity: "thuanlephuc152@gmail.com"
        auth_password: "svpumtlqxsigkjyj"
        auth_username: "thuanlephuc152@gmail.com"
        send_resolved: true

  - name: 'slack-notifications'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#mornitoring-png-stack'
        send_resolved: true
        icon_url: "https://avatars3.githubusercontent.com/u/3380462"
        title: |-
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
          {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
            {{" "}}(
            {{- with .CommonLabels.Remove .GroupLabels.Names }}
              {{- range $index, $label := .SortedPairs -}}
                {{ if $index }}, {{ end }}
                {{- $label.Name }}="{{ $label.Value -}}"
              {{- end }}
            {{- end -}}
            )
          {{- end }}
        text: >-
          {{ range .Alerts -}}
          *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

          *Description:* {{ .Annotations.description }}

          *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`{{ end }}
          {{ end }}
