server:
  http_listen_port: 9080
  grpc_listen_port: 9096

positions:
  filename: /tmp/positions.yaml  # Track the last read positions of logs

clients:
  - url: https://loki.lptdevops.website/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log  
