networks:
  PrviNetwork:
    external: true

volumes:
  elasticsearch-data:

secrets:
  elasticsearch.keystore:
    file: ./secrets/keystore/elasticsearch.keystore
  elasticsearch.service_tokens:
    file: ./secrets/service_tokens
  kibana.keystore:
    file: ./secrets/keystore/kibana.keystore

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
    restart: always
    environment:
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ELASTIC_CLUSTER_NAME: ${CLUSTER_NAME}
      ELASTIC_NODE_NAME: ${NODE_NAME}
      ELASTICSEARCH_PORT: ${ES_PORT}
      LS_JAVA_OPTS: -Xms256m -Xmx256m

    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
    secrets:
      - source: elasticsearch.keystore
        target: /usr/share/elasticsearch/config/elasticsearch.keystore
      - source: elasticsearch.service_tokens
        target: /usr/share/elasticsearch/config/service_tokens
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - PrviNetwork
    labels:
      - "traefik.http.routers.elasticsearch-secure.rule=Host(`elasticsearch.lptdevops.website`)"
      - "traefik.http.routers.elasticsearch-secure.entrypoints=websecure"
      - "traefik.http.routers.elasticsearch-secure.tls=true"
      - "traefik.http.routers.elasticsearch-secure.tls.certresolver=leresolver"

      - "traefik.http.routers.elasticsearch.rule=Host(`elasticsearch.lptdevops.website`)"
      - "traefik.http.routers.elasticsearch.entrypoints=web"
      - "traefik.http.routers.elasticsearch.middlewares=redirect-to-https"

      - "traefik.http.services.elasticsearch.loadbalancer.server.port=9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.2
    restart: always
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ELASTICSEARCH_HOST_PORT: https://elasticsearch.lptdevops.website
      LS_JAVA_OPTS: -Xms256m -Xmx256m
    ports:
      - "5044:5044"
      - "9600:9600"
    labels:
      - "traefik.http.routers.logstash-secure.rule=Host(`logstash.lptdevops.website`)"
      - "traefik.http.routers.logstash-secure.entrypoints=websecure"
      - "traefik.http.routers.logstash-secure.tls=true"
      - "traefik.http.routers.logstash-secure.tls.certresolver=leresolver"

      - "traefik.http.routers.logstash.rule=Host(`logstash.lptdevops.website`)"
      - "traefik.http.routers.logstash.entrypoints=web"
      - "traefik.http.routers.logstash.middlewares=redirect-to-https"

      - "traefik.http.services.logstash.loadbalancer.server.port=5044"
    networks:
      - PrviNetwork

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.2
    restart: always
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    secrets:
      - source: kibana.keystore
        target: /usr/share/kibana/config/kibana.keystore
    environment:
      ELASTICSEARCH_HOST_PORT: https://elasticsearch.lptdevops.website
      KIBANA_PORT: 5601
    env_file:
      - ./secrets/.env.kibana.token
    ports:
      - "5601:5601"
    labels:
      - "traefik.http.routers.kibana-secure.rule=Host(`kibana.lptdevops.website`)"
      - "traefik.http.routers.kibana-secure.entrypoints=websecure"
      - "traefik.http.routers.kibana-secure.tls=true"
      - "traefik.http.routers.kibana-secure.tls.certresolver=leresolver"

      - "traefik.http.routers.kibana.rule=Host(`kibana.lptdevops.website`)"
      - "traefik.http.routers.kibana.entrypoints=web"
      - "traefik.http.routers.kibana.middlewares=redirect-to-https"

      - "traefik.http.services.kibana.loadbalancer.server.port=5601"
    networks:
      - PrviNetwork
