global:
  scrape_interval: 20s 
  evaluation_interval: 15s
  scrape_timeout: 18s 

alerting:
  alertmanagers:
    - static_configs:
      - targets: ["alert-manager.lptdevops.website"]

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: "monitor-cluster"
    static_configs:
      - targets: ["prometheus.lptdevops.website:9100"] # Node exporter port
        labels:
          hostname: PrometheusProd
          type: docker
      - targets: ["100.27.26.94:9100"] # Node exporter port
        labels:
          hostname: TestProd
          type: docker
